[2023-12-22T04:16:11.918+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v0222-2.insert_into_postgres_table manual__2023-12-22T04:16:07.382780+00:00 [queued]>
[2023-12-22T04:16:11.945+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v0222-2.insert_into_postgres_table manual__2023-12-22T04:16:07.382780+00:00 [queued]>
[2023-12-22T04:16:11.947+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2023-12-22T04:16:11.976+0000] {taskinstance.py:2192} INFO - Executing <Task(PostgresOperator): insert_into_postgres_table> on 2023-12-22 04:16:07.382780+00:00
[2023-12-22T04:16:11.985+0000] {standard_task_runner.py:60} INFO - Started process 11088 to run task
[2023-12-22T04:16:11.995+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v0222-2', 'insert_into_postgres_table', 'manual__2023-12-22T04:16:07.382780+00:00', '--job-id', '194', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_operator.py', '--cfg-path', '/tmp/tmpnv5y0jcy']
[2023-12-22T04:16:12.001+0000] {standard_task_runner.py:88} INFO - Job 194: Subtask insert_into_postgres_table
[2023-12-22T04:16:12.098+0000] {task_command.py:423} INFO - Running <TaskInstance: dag_with_postgres_operator_v0222-2.insert_into_postgres_table manual__2023-12-22T04:16:07.382780+00:00 [running]> on host dd88aaafc1d9
[2023-12-22T04:16:12.270+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='sarwar' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator_v0222-2' AIRFLOW_CTX_TASK_ID='insert_into_postgres_table' AIRFLOW_CTX_EXECUTION_DATE='2023-12-22T04:16:07.382780+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-22T04:16:07.382780+00:00'
[2023-12-22T04:16:12.272+0000] {sql.py:276} INFO - Executing: 
            insert into dag_runs (dt, dag_id) values('2023-12-22', 'dag_with_postgres_operator_v0222-2' )
        
[2023-12-22T04:16:12.296+0000] {base.py:83} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-12-22T04:16:12.317+0000] {base.py:83} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-12-22T04:16:12.336+0000] {sql.py:432} INFO - Running statement: 
            insert into dag_runs (dt, dag_id) values('2023-12-22', 'dag_with_postgres_operator_v0222-2' )
        , parameters: None
[2023-12-22T04:16:12.345+0000] {sql.py:441} INFO - Rows affected: 1
[2023-12-22T04:16:12.370+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_operator_v0222-2, task_id=insert_into_postgres_table, execution_date=20231222T041607, start_date=20231222T041611, end_date=20231222T041612
[2023-12-22T04:16:12.454+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2023-12-22T04:16:12.485+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
