[2023-12-22T04:18:40.466+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v0222-2.insert_into_postgres_table manual__2023-12-22T04:18:36.513067+00:00 [queued]>
[2023-12-22T04:18:40.489+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v0222-2.insert_into_postgres_table manual__2023-12-22T04:18:36.513067+00:00 [queued]>
[2023-12-22T04:18:40.493+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2023-12-22T04:18:40.524+0000] {taskinstance.py:2192} INFO - Executing <Task(PostgresOperator): insert_into_postgres_table> on 2023-12-22 04:18:36.513067+00:00
[2023-12-22T04:18:40.543+0000] {standard_task_runner.py:60} INFO - Started process 11276 to run task
[2023-12-22T04:18:40.549+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v0222-2', 'insert_into_postgres_table', 'manual__2023-12-22T04:18:36.513067+00:00', '--job-id', '196', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_operator.py', '--cfg-path', '/tmp/tmpyeej68k2']
[2023-12-22T04:18:40.557+0000] {standard_task_runner.py:88} INFO - Job 196: Subtask insert_into_postgres_table
[2023-12-22T04:18:40.688+0000] {task_command.py:423} INFO - Running <TaskInstance: dag_with_postgres_operator_v0222-2.insert_into_postgres_table manual__2023-12-22T04:18:36.513067+00:00 [running]> on host dd88aaafc1d9
[2023-12-22T04:18:40.874+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='sarwar' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator_v0222-2' AIRFLOW_CTX_TASK_ID='insert_into_postgres_table' AIRFLOW_CTX_EXECUTION_DATE='2023-12-22T04:18:36.513067+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-22T04:18:36.513067+00:00'
[2023-12-22T04:18:40.877+0000] {sql.py:276} INFO - Executing: 
            insert into dag_runs (dt, dag_id) values('2023-12-22', 'dag_with_postgres_operator_v0222-2' )
        
[2023-12-22T04:18:40.900+0000] {base.py:83} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-12-22T04:18:40.921+0000] {base.py:83} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-12-22T04:18:40.941+0000] {sql.py:432} INFO - Running statement: 
            insert into dag_runs (dt, dag_id) values('2023-12-22', 'dag_with_postgres_operator_v0222-2' )
        , parameters: None
[2023-12-22T04:18:40.949+0000] {sql.py:441} INFO - Rows affected: 1
[2023-12-22T04:18:40.971+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_operator_v0222-2, task_id=insert_into_postgres_table, execution_date=20231222T041836, start_date=20231222T041840, end_date=20231222T041840
[2023-12-22T04:18:41.021+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2023-12-22T04:18:41.062+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
